[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "anuska06-bot", email = "sahaanuska0@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.20.0",
    "fastapi>=0.141.1",
    "geoalchemy2>=0.20.0",
    "httpx>=0.28.1",
    "joblib>=1.4.0",
    "opencv-python-headless>=5.0.0.93",
    "pandas>=2.2.0",
    "pillow>=12.3.0",
    "psycopg[binary]>=3.3.6",
    "pydantic>=2.13.5",
    "pytest>=9.1.1",
    "python-multipart>=0.0.32",
    "scikit-learn>=1.5.0",
    "shapely>=2.1.2",
    "sqlalchemy>=2.0",
    "uvicorn>=0.53.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
